---
server:
  port: 9199
  servlet:
    context-path: /pets
message: Hello from github
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size:  2
owner-service:
  ribbon:
    listOfServers: localhost:9198,localhost:9298
